name: SneakyDiscordLink
version: "1.0"
main: com.danidipp.sneakydiscordlink.SneakyDiscordLink
api-version: "1.20"
authors:
  - DaniDipp
description: "Paper plugin for linking Minecraft and Discord accounts"
